[1]
sample_info = "Sample 1"
solvent = "CDCl3"
nmr_experiments = [
    "MULTISUPPDC_f",
]

[2]
sample_info = "Sample 2"
solvent = "CH3CN"
nmr_experiments = [
    "PROTON_f",
    { parameters = "MULTISUPPDC_f", num_scans = 64, acqupars.ds = 4 },
]

[3]
sample_info = "Sample 3"
solvent     = "CH3CN"

    [[3.nmr_experiments]]
    parameters  = "PROTON_f"
    acqupars.d1 = 1
    acqupars.sw = 10

    [[3.nmr_experiments]]
    parameters   = "MULTISUPPDC_f"
    num_scans    = 64
    pp_threshold = 0.008
    field_presat = 20

[[4.nmr_experiments]]
parameters = "K_WETDC"
l30        = 2
num_scans  = 64
